services:
  - type: web
    name: isdamarket-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      # Static assets - serve directly with exact paths
      - type: rewrite
        source: /static/*
        destination: /static/:splat
      - type: rewrite
        source: /favicon.ico
        destination: /favicon.ico
      - type: rewrite
        source: /logo192.png
        destination: /logo192.png
      - type: rewrite
        source: /logo512.png
        destination: /logo512.png
      - type: rewrite
        source: /manifest.json
        destination: /manifest.json
      - type: rewrite
        source: /robots.txt
        destination: /robots.txt
      - type: rewrite
        source: /asset-manifest.json
        destination: /asset-manifest.json
      # Catch-all route - MUST be last to handle SPA routing
      # This ensures all routes serve index.html for client-side routing
      - type: rewrite
        source: /*
        destination: /index.html
